# Copyright 2022-present, Lorenzo Bonicelli, Pietro Buzzega, Matteo Boschini, Angelo Porrello, Simone Calderara.
# All rights reserved.
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

"""
This module contains the best hyperparameters on a small selection of datasets and models.

The hyperparameters are organized in a dictionary with the following structure:
      {
            'dataset_name': {
                  'model_name': {
                        'buffer_size': {
                              'hyperparameter_name': hyperparameter_value
                        }
                  }
            }
      }

Todolist:
      * Add more hyperparameters
      * Add more datasets
      * Add more models
"""

best_args = {
    'rot-mnist': {
        'si': {-1: {'lr': 0.1,
                    'c': 1.0,
                    'xi': 1.0,
                    'batch_size': 128,
                    'n_epochs': 1}},
        'er': {200: {'lr': 0.2,
                     'minibatch_size': 128,
                     'batch_size': 128,
                     'n_epochs': 1},
               500: {'lr': 0.2,
                     'minibatch_size': 128,
                     'batch_size': 128,
                     'n_epochs': 1},
               5120: {'lr': 0.2,
                      'minibatch_size': 128,
                      'batch_size': 128,
                      'n_epochs': 1}},
        'gem': {200: {'lr': 0.01,
                      'gamma': 0.5,
                      'batch_size': 128,
                      'n_epochs': 1},
                500: {'lr': 0.01, 'gamma': 0.5, 'batch_size': 128,
                      'n_epochs': 1},
                5120: {'lr': 0.01, 'gamma': 0.5, 'batch_size': 128,
                       'n_epochs': 1}},
        'agem': {200: {'lr': 0.1,
                       'minibatch_size': 128,
                       'batch_size': 128,
                       'n_epochs': 1},
                 500: {'lr': 0.3,
                       'minibatch_size': 128,
                       'batch_size': 128,
                       'n_epochs': 1},
                 5120: {'lr': 0.3,
                        'minibatch_size': 128,
                        'batch_size': 128,
                        'n_epochs': 1}},
        'hal': {200: {'lr': 0.1,
                      'minibatch_size': 128,
                      'batch_size': 128,
                      'hal_lambda': 0.2,
                      'beta': 0.5,
                      'gamma': 0.1,
                      'n_epochs': 1},
                500: {'lr': 0.1,
                      'minibatch_size': 128,
                      'batch_size': 128,
                      'hal_lambda': 0.1,
                      'beta': 0.5,
                      'gamma': 0.1,
                      'n_epochs': 1},
                5120: {'lr': 0.1,
                       'minibatch_size': 128,
                       'batch_size': 128,
                       'hal_lambda': 0.1,
                       'beta': 0.3,
                       'gamma': 0.1,
                       'n_epochs': 1}},
        'gss': {200: {'lr': 0.2,
                      'minibatch_size': 10,
                      'gss_minibatch_size': 128,
                      'batch_size': 128,
                      'batch_num': 1,
                      'n_epochs': 1},
                500: {'lr': 0.2,
                      'minibatch_size': 128,
                      'gss_minibatch_size': 128,
                      'batch_size': 128,
                      'batch_num': 1,
                      'n_epochs': 1},
                5120: {'lr': 0.2,
                       'minibatch_size': 128,
                       'gss_minibatch_size': 128,
                       'batch_size': 128,
                       'batch_num': 1,
                       'n_epochs': 1}},
        'fdr': {200: {'lr': 0.2,
                      'minibatch_size': 128,
                      'alpha': 1.0,
                      'batch_size': 128,
                      'n_epochs': 1},
                500: {'lr': 0.2,
                      'minibatch_size': 128,
                      'alpha': 0.3,
                      'batch_size': 128,
                      'n_epochs': 1},
                5120: {'lr': 0.2,
                       'minibatch_size': 128,
                       'alpha': 1,
                       'batch_size': 128,
                       'n_epochs': 1}},
        'der': {200: {'lr': 0.2,
                      'minibatch_size': 128,
                      'alpha': 1.0,
                      'batch_size': 128,
                      'n_epochs': 1},
                500: {'lr': 0.2,
                      'minibatch_size': 128,
                      'alpha': 0.5,
                      'batch_size': 128,
                      'n_epochs': 1},
                5120: {'lr': 0.2,
                       'minibatch_size': 128,
                       'alpha': 0.5,
                       'batch_size': 128,
                       'n_epochs': 1}},
        'derpp': {200: {'lr': 0.1,
                        'minibatch_size': 128,
                        'alpha': 1.0,
                        'beta': 0.5,
                        'batch_size': 128,
                        'n_epochs': 1},
                  500: {'lr': 0.2,
                        'minibatch_size': 128,
                        'alpha': 0.5,
                        'beta': 1.0,
                        'batch_size': 128,
                        'n_epochs': 1},
                  5120: {'lr': 0.2,
                         'minibatch_size': 128,
                         'alpha': 0.5,
                         'beta': 0.5,
                         'batch_size': 128,
                         'n_epochs': 1}},
        'derpp': {200: {'lr': 0.03,
                        'minibatch_size': 128,
                        'alpha': 0.01,
                        'beta': 0.3,
                        'batch_size': 128,
                        'n_epochs': 1},
                  500: {'lr': 0.03,
                        'minibatch_size': 128,
                        'alpha': 0.01,
                        'beta': 0.3,
                        'batch_size': 128,
                        'n_epochs': 1},
                  5120: {'lr': 0.03,
                        'minibatch_size': 128,
                        'alpha': 0.01,
                        'beta': 0.3,
                        'batch_size': 128,
                        'n_epochs': 1}}},
    'seq-cifar10': {
                    'si': {-1: {'lr': 0.03,
                                'c': 0.5,
                                'xi': 1.0,
                                'batch_size': 32,
                                'n_epochs': 50}},
                    'lwf': {-1: {'lr': 0.01,
                                 'alpha': 3.0,
                                 'softmax_temp': 2.0,
                                 'batch_size': 32,
                                 'n_epochs': 50,
                                 'optim_wd': 0.0005}},
                    'pnn': {-1: {'lr': 0.03, 'batch_size': 32,
                                 'n_epochs': 50}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           500: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           5120: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50}},
                    'gem': {200: {'lr': 0.03,
                                  'gamma': 0.5,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            500: {'lr': 0.03, 'gamma': 0.5,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            5120: {'lr': 0.03, 'gamma': 0.5,
                                   'batch_size': 32,
                                   'n_epochs': 50}},
                    'agem': {200: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50},
                             500: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50},
                             5120: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 50}},
                    'hal': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'hal_lambda': 0.2,
                                  'beta': 0.5,
                                  'gamma': 0.1,
                                  'steps_on_anchors': 100,
                                  'finetuning_epochs': 1},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'hal_lambda': 0.1,
                                  'beta': 0.3,
                                  'gamma': 0.1,
                                  'steps_on_anchors': 100,
                                  'finetuning_epochs': 1},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50,
                                   'hal_lambda': 0.1,
                                   'beta': 0.3,
                                   'gamma': 0.1,
                                   'steps_on_anchors': 100,
                                   'finetuning_epochs': 1}},
                    'gss': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'gss_minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'batch_num': 1},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'gss_minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50,
                                  'batch_num': 1},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'gss_minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 1,
                                   'batch_num': 1}},
                    
                    'icarl': {200: {'lr': 0.1,
                                    'minibatch_size': 0,
                                    'softmax_temp': 2.0,
                                    'optim_wd': 0.00001,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              500: {'lr': 0.1,
                                    'minibatch_size': 0,
                                    'softmax_temp': 2.0,
                                    'optim_wd': 0.00001,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              5120: {'lr': 0.03,
                                     'minibatch_size': 0,
                                     'softmax_temp': 2.0,
                                     'optim_wd': 0.00001,
                                     'batch_size': 32,
                                     'n_epochs': 50}},
                    'fdr': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 1,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'alpha': 0.3,
                                   'batch_size': 32,
                                   'n_epochs': 50}},
                    'der': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'alpha': 0.3,
                                   'batch_size': 32,
                                   'n_epochs': 50}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              5120: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.1,
                                     'beta': 1.0,
                                     'batch_size': 32,
                                     'n_epochs': 50}}},
    'seq-tinyimg': {
                    'si': {-1: {'lr': 0.03,
                                'c': 0.5,
                                'xi': 1.0,
                                'batch_size': 32,
                                'n_epochs': 100}},
                    'lwf': {-1: {'lr': 0.01,
                                 'alpha': 1.0,
                                 'softmax_temp': 2.0,
                                 'batch_size': 32,
                                 'n_epochs': 100,
                                 'optim_wd': 0.0005}},
                    'pnn': {-1: {'lr': 0.03, 'batch_size': 32,
                                 'n_epochs': 100}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 100},
                           500: {'lr': 0.03,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 100},
                           5120: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 100}},
                    'agem': {200: {'lr': 0.01,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 100},
                             500: {'lr': 0.01,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 100},
                             5120: {'lr': 0.01,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100}},
                    'icarl': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'softmax_temp': 2.0,
                                    'optim_wd': 0.00001,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'softmax_temp': 2.0,
                                    'optim_wd': 0.00001,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              5120: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'softmax_temp': 2.0,
                                     'optim_wd': 0.00001,
                                     'batch_size': 32,
                                     'n_epochs': 100}},
                    'fdr': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 100},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 1,
                                  'batch_size': 32,
                                  'n_epochs': 100},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'alpha': 0.3,
                                   'batch_size': 32,
                                   'n_epochs': 100}},
                    'der': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'softmax_temp': 2.0,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 100},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 100},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'alpha': 0.1,
                                   'batch_size': 32,
                                   'n_epochs': 100}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 1.0,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              5120: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.1,
                                     'beta': 0.5,
                                     'batch_size': 32,
                                     'n_epochs': 100}}},
    'seq-cifar100': {
        'er': {
            500: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0},
            2000: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0}
        },
        'icarl': {
            500: {'lr': 0.3, 'optim_mom': 0, 'optim_wd': 1e-05},
            2000: {'lr': 0.3, 'optim_mom': 0, 'optim_wd': 1e-05}
        },
        'lwf': {
            -1: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 5e-4},
        },
        'der': {
            500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.3},
            2000: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.3}
        },
        'derpp': {
            500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5},
            2000: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5}
        },
    }

}
